name: deploy-to-heroku
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    env:
      DJANGO_SETTINGS_MODULE: 'settings'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: python manage.py makemigrations
      - run: python manage.py migrate
      - run: python manage.py test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "b00kworm"
          branch: staging
      - id: migrate_database
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - id: after_deploy
        run: "heroku ps:scale web=1 --app b00kworm"
